### ISSUE TITLE
[Fix] S3 AccessDenied 

### ISSUE THREAD

**Issue by MiaaaChen** [Tonyrj3268/Processes#58]
@Tonyrj3268 `PATCH /api/user` 頭貼沒辦法上傳 
更新個人檔案後的 avatarURL 是空的，沒有得到網址

<img width="1095" alt="error message" src="https://github.com/user-attachments/assets/aae505f8-eef1-4525-a502-60974958a1ba">

**Comment by Tonyrj3268** [comment]
已解決
方法：調整IAM s3權限
